#!/usr/bin/env bash

set -Eeuo pipefail

xdg_data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
install_dir="$xdg_data_home/oh-my-zsh"
custom_plugins_dir="$install_dir/custom/plugins"

install_or_update_plugin() {
  local name="$1"
  local repository="$2"
  local destination="$custom_plugins_dir/$name"

  if [[ -d "$destination/.git" ]]; then
    printf 'Updating %s...\n' "$name"
    git -C "$destination" pull --ff-only
  else
    printf 'Installing %s...\n' "$name"
    git clone --depth=1 "$repository" "$destination"
  fi
}

mkdir -p "$xdg_data_home"

if [[ -d "$install_dir/.git" ]]; then
  printf 'Updating Oh My Zsh...\n'
  git -C "$install_dir" pull --ff-only
else
  printf 'Installing Oh My Zsh...\n'
  git clone \
    --depth=1 \
    https://github.com/ohmyzsh/ohmyzsh.git \
    "$install_dir"
fi

mkdir -p "$custom_plugins_dir"

install_or_update_plugin \
  zsh-autosuggestions \
  https://github.com/zsh-users/zsh-autosuggestions.git

install_or_update_plugin \
  zsh-syntax-highlighting \
  https://github.com/zsh-users/zsh-syntax-highlighting.git