#!/usr/bin/env bash

set -Eeuo pipefail

if command -v nix >/dev/null 2>&1; then
  printf 'Nix is already installed.\n'
  exit 0
fi

curl \
  --proto '=https' \
  --tlsv1.2 \
  --fail \
  --show-error \
  --location \
  https://nixos.org/nix/install |
  sh -s -- --daemon